services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: tunehub_symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/app
    depends_on:
      - php
    networks:
      - tunehub_symfony

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: tunehub_symfony_php
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    depends_on:
      - mysql
      - redis
    networks:
      - tunehub_symfony

  mysql:
    image: mysql:8.4
    container_name: tunehub_symfony_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tunehub_symfony

  minio:
    image: minio/minio:latest
    container_name: tunehub-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: '${AWS_ACCESS_KEY_ID}'
      MINIO_ROOT_PASSWORD: '${AWS_SECRET_ACCESS_KEY}'
    volumes:
      - minio_data:/data
    networks:
      - tunehub_symfony

  redis:
    image: redis:7-alpine
    container_name: tunehub_symfony_redis
    ports:
      - "6380:6379"
    networks:
      - tunehub_symfony

volumes:
  mysql_data:
  minio_data:

networks:
  tunehub_symfony:
    driver: bridge
